### ISSUE TITLE
Redundant class in nav-item component

### ISSUE THREAD

**Issue by JN0122** [wiktorrudzki/Frontend-projekt#12]
W każdym linku oprócz aktywnego pojawia się klasa _false_.
<img width="650" alt="Screenshot 2022-11-30 at 22 18 22" src="https://user-images.githubusercontent.com/33033063/204910369-421ad874-05aa-4670-b24e-993bfba569d6.png">

**Comment by wiktorrudzki** [comment]
wynika to z tego, ze kazdy link sprawdza czy po kolei czy jest aktywny, jesli jest - nadaje mu klase active, jesli nie jest instrukcja warunkowa zwraca false - stad tez klasa false, moge to zmienic na "" lub null, ale chyba nie jestem w stanie totalnie to usunac dla warunkowego ustawienia klasy. Z tego co sie orientuje najpopularniejszym rozwiazaniem jest nadanie po prostu pustego stringa i tak tez zrobilem, ale jesli znasz lepsze rozwiazanie to daj znac i mozna je zaimplementowac
